#!/usr/bin/env bash
#Bad luck
counter=1
while ((counter<=20))
do
	case $counter in
	
		4)
			echo "$counter"
			echo "bad luck in China"
			;;
		9)
			echo "$counter"
			echo "bad luck in Japan"
			;;
		17)
			echo "$counter"
			echo "bad luck in Italy"
			;;
		*)
			echo "$counter"
			;;
		esac
		((counter++))
done
